import Head from "next/head";
import { GlobalSytle } from "@/styles/globals";
import { GlobalProvider } from "@/hooks/context/global";
import type { AppProps } from "next/app";

export default function App({ Component, pageProps }: AppProps) {
  return (
    <div>
      <Head>
        <title>OrderFlex</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <GlobalProvider>
        <GlobalSytle />
        <Component {...pageProps} />
      </GlobalProvider>
    </div>
  );
}
